### ISSUE TITLE
Tags pages

### ISSUE THREAD

**Issue by orels1** [orels1/v3.cogs.red#25]
## List of tags
- Load tags from the api to the vuex store, same way as in the `Cogs` component (API docs are here https://orels1.github.io/Red-Portal/#api-misc-getPopularTags)
- Display the list of all tags with the cog count. 
- The markup should be somewhat similar to http://cogs.red/cogs/tags/ i.e. really basic list
- Clicking on the tag should navigate you to the /search/<tagName> references on how to do that programmatically - in the `Navbar` component.
- The page should be accessible at /tags

_optionally_

- Replace the last tag in the `Statsbar` component with a "show all tags" link to `/tags`, similar to https://cogs.red/cogs/

**Comment by narian** [comment]
#64

**Comment by orels1** [comment]
done in #64
